### ISSUE TITLE
Back dates should be disable from the date picker

### ISSUE THREAD

**Issue by Shweta91kubde** [lokeshpathrabe/vaccine-finder#1]
User can select the previous dates and app is also retuning the data for back dates.

![IMG_20210531_214430](https://user-images.githubusercontent.com/85124937/120219834-76721d00-c259-11eb-88c8-830c357493fb.jpg)

**Comment by RishikeshVedpathak** [comment]
@lokeshpathrabe you can assign this to me.
Generated PR for this - https://github.com/lokeshpathrabe/vaccine-finder/pull/5
